<#
.SYNOPSIS
    Generates a WiX v4 fragment for widget provider files.

.DESCRIPTION
    Scans bin\WidgetProvider\ and generates installer\WidgetProviderFiles.wxs
    with Component/File entries for every file. This replaces WiX heat which
    was removed in WiX v4.

    Called automatically by build.bat Step 6 when the widget feature is included.
#>

param(
    [string]$SourceDir = (Join-Path (Split-Path $PSScriptRoot -Parent) "bin\WidgetProvider"),
    [string]$OutputFile = (Join-Path $PSScriptRoot "WidgetProviderFiles.wxs")
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $SourceDir)) {
    Write-Error "Source directory not found: $SourceDir"
}

# Collect all files relative to SourceDir
$allFiles = Get-ChildItem $SourceDir -File -Recurse
$topLevelFiles = Get-ChildItem $SourceDir -File
$subdirs = Get-ChildItem $SourceDir -Directory

Write-Host "Harvesting $($allFiles.Count) widget provider files..."

# Helper: make a valid WiX Id from a filename (replace invalid chars)
function Get-WixId {
    param([string]$Name, [string]$Prefix = "wp")
    $id = "${Prefix}_$($Name -replace '[^a-zA-Z0-9_.]', '_')"
    # WiX IDs max 72 chars
    if ($id.Length -gt 72) { $id = $id.Substring(0, 72) }
    return $id
}

# Track IDs to avoid duplicates
$usedIds = @{}
function Get-UniqueId {
    param([string]$Base)
    $id = $Base
    $counter = 1
    while ($usedIds.ContainsKey($id)) {
        $id = "${Base}_$counter"
        $counter++
    }
    $usedIds[$id] = $true
    return $id
}

# Build the XML
$xml = [System.Text.StringBuilder]::new()
[void]$xml.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$xml.AppendLine('<!--')
[void]$xml.AppendLine('  Auto-generated by harvest-widget-files.ps1 - DO NOT EDIT')
[void]$xml.AppendLine('  Regenerated each build by the build pipeline (Step 6).')
[void]$xml.AppendLine('-->')
[void]$xml.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
[void]$xml.AppendLine('  <Fragment>')
[void]$xml.AppendLine('    <ComponentGroup Id="WidgetProviderFiles">')

# Top-level files -> INSTALLFOLDER
foreach ($file in $topLevelFiles) {
    $id = Get-UniqueId (Get-WixId $file.Name)
    $fileId = Get-UniqueId (Get-WixId $file.Name "wpf")
    $source = "bin/WidgetProvider/$($file.Name)"
    [void]$xml.AppendLine("      <Component Id=`"$id`" Directory=`"WidgetProviderDir`" Guid=`"*`">")
    [void]$xml.AppendLine("        <File Id=`"$fileId`" Source=`"$source`" KeyPath=`"yes`" />")
    [void]$xml.AppendLine("      </Component>")
}

# Subdirectory files -> need Directory refs
foreach ($subdir in $subdirs) {
    $dirId = Get-UniqueId (Get-WixId $subdir.Name "wpd")
    $subFiles = Get-ChildItem $subdir.FullName -File -Recurse

    foreach ($file in $subFiles) {
        $relPath = $file.FullName.Substring($SourceDir.Length + 1).Replace('\', '/')
        $id = Get-UniqueId (Get-WixId "$($subdir.Name)_$($file.Name)")
        $fileId = Get-UniqueId (Get-WixId "$($subdir.Name)_$($file.Name)" "wpf")
        $source = "bin/WidgetProvider/$relPath"
        [void]$xml.AppendLine("      <Component Id=`"$id`" Directory=`"$dirId`" Guid=`"*`">")
        [void]$xml.AppendLine("        <File Id=`"$fileId`" Source=`"$source`" KeyPath=`"yes`" />")
        [void]$xml.AppendLine("      </Component>")
    }
}

[void]$xml.AppendLine('    </ComponentGroup>')
[void]$xml.AppendLine('  </Fragment>')

# Directory definitions for subdirectories
if ($subdirs.Count -gt 0) {
    [void]$xml.AppendLine('')
    [void]$xml.AppendLine('  <!-- Subdirectories under INSTALLFOLDER for widget provider locale files -->')
    [void]$xml.AppendLine('  <Fragment>')
    [void]$xml.AppendLine('    <DirectoryRef Id="WidgetProviderDir">')

    # Reset used IDs for directory names (they're in a different scope)
    foreach ($subdir in $subdirs) {
        $dirId = Get-WixId $subdir.Name "wpd"
        # Ensure we use the same ID as in the component references above
        [void]$xml.AppendLine("      <Directory Id=`"$dirId`" Name=`"$($subdir.Name)`" />")
    }

    [void]$xml.AppendLine('    </DirectoryRef>')
    [void]$xml.AppendLine('  </Fragment>')
}

[void]$xml.AppendLine('</Wix>')

# Write output
Set-Content -Path $OutputFile -Value $xml.ToString() -Encoding UTF8
Write-Host "Generated $OutputFile ($($allFiles.Count) files, $($subdirs.Count) subdirectories)"
